name: Use .npmrc
description: Create your .npmrc when running CI/CD Github Actions
author: LacheRo
inputs:
  npm-token:
    description: 'your npm token'
    required: true
  directories:
    description: 'list of directories comma seperated (i.e. backend,frontend)'
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ./{test1,test2}/.npmrc
      shell: bash
